version: '3'
services: 
    ghost:
      image: ghost:1-alpine
      ports:
        - 2368:2368
      depends_on:
        - "db"
      environment:
        # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
        - database__client= mysql
        - database__connection__host=db
        - database__connection__user=root
        - database__connection__password=example
        - database__connection__database=ghost

    db:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"